version: '3.8'

services:
  ldap:
    image: osixia/openldap:latest
    container_name: ldap-server
    hostname: ldap-server
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "Example Organization"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin123"
      LDAP_CONFIG_PASSWORD: "config123"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldif:/ldif:ro
    command: ["--copy-service"]
    restart: unless-stopped
    networks:
      - ldap-network
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-b", "dc=example,dc=com", "-D", "cn=admin,dc=example,dc=com", "-w", "admin123"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ldap_data:
    driver: local
  ldap_config:
    driver: local

networks:
  ldap-network:
    driver: bridge
